// Generated by view binder compiler. Do not edit!
package net.hearnsoft.setupwizard.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager2.widget.ViewPager2;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import net.hearnsoft.setupwizard.R;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final FrameLayout navBar;

  @NonNull
  public final MaterialButton navNext;

  @NonNull
  public final MaterialButton navPriv;

  @NonNull
  public final ViewPager2 pager;

  private ActivityMainBinding(@NonNull FrameLayout rootView, @NonNull FrameLayout navBar,
      @NonNull MaterialButton navNext, @NonNull MaterialButton navPriv, @NonNull ViewPager2 pager) {
    this.rootView = rootView;
    this.navBar = navBar;
    this.navNext = navNext;
    this.navPriv = navPriv;
    this.pager = pager;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.nav_bar;
      FrameLayout navBar = ViewBindings.findChildViewById(rootView, id);
      if (navBar == null) {
        break missingId;
      }

      id = R.id.nav_next;
      MaterialButton navNext = ViewBindings.findChildViewById(rootView, id);
      if (navNext == null) {
        break missingId;
      }

      id = R.id.nav_priv;
      MaterialButton navPriv = ViewBindings.findChildViewById(rootView, id);
      if (navPriv == null) {
        break missingId;
      }

      id = R.id.pager;
      ViewPager2 pager = ViewBindings.findChildViewById(rootView, id);
      if (pager == null) {
        break missingId;
      }

      return new ActivityMainBinding((FrameLayout) rootView, navBar, navNext, navPriv, pager);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
