// Generated by view binder compiler. Do not edit!
package net.hearnsoft.setupwizard.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.RadioGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import net.hearnsoft.setupwizard.R;

public final class FragmentGestureViewBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final ImageView gestureView;

  @NonNull
  public final RadioGroup selectorItems;

  private FragmentGestureViewBinding(@NonNull FrameLayout rootView, @NonNull ImageView gestureView,
      @NonNull RadioGroup selectorItems) {
    this.rootView = rootView;
    this.gestureView = gestureView;
    this.selectorItems = selectorItems;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentGestureViewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentGestureViewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_gesture_view, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentGestureViewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.gesture_view;
      ImageView gestureView = ViewBindings.findChildViewById(rootView, id);
      if (gestureView == null) {
        break missingId;
      }

      id = R.id.selector_items;
      RadioGroup selectorItems = ViewBindings.findChildViewById(rootView, id);
      if (selectorItems == null) {
        break missingId;
      }

      return new FragmentGestureViewBinding((FrameLayout) rootView, gestureView, selectorItems);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
