// Generated by view binder compiler. Do not edit!
package net.hearnsoft.setupwizard.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import net.hearnsoft.setupwizard.R;
import net.hearnsoft.setupwizard.widgets.SuperTextView;

public final class FragmentIntroViewBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final LinearLayout banner;

  @NonNull
  public final MaterialButton welcomeAccessibility;

  @NonNull
  public final MaterialButton welcomeEmergencyCall;

  @NonNull
  public final MaterialButton welcomeLanguage;

  @NonNull
  public final RelativeLayout welcomeLayout;

  @NonNull
  public final SuperTextView welcomeText;

  private FragmentIntroViewBinding(@NonNull FrameLayout rootView, @NonNull LinearLayout banner,
      @NonNull MaterialButton welcomeAccessibility, @NonNull MaterialButton welcomeEmergencyCall,
      @NonNull MaterialButton welcomeLanguage, @NonNull RelativeLayout welcomeLayout,
      @NonNull SuperTextView welcomeText) {
    this.rootView = rootView;
    this.banner = banner;
    this.welcomeAccessibility = welcomeAccessibility;
    this.welcomeEmergencyCall = welcomeEmergencyCall;
    this.welcomeLanguage = welcomeLanguage;
    this.welcomeLayout = welcomeLayout;
    this.welcomeText = welcomeText;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentIntroViewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentIntroViewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_intro_view, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentIntroViewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.banner;
      LinearLayout banner = ViewBindings.findChildViewById(rootView, id);
      if (banner == null) {
        break missingId;
      }

      id = R.id.welcome_accessibility;
      MaterialButton welcomeAccessibility = ViewBindings.findChildViewById(rootView, id);
      if (welcomeAccessibility == null) {
        break missingId;
      }

      id = R.id.welcome_emergency_call;
      MaterialButton welcomeEmergencyCall = ViewBindings.findChildViewById(rootView, id);
      if (welcomeEmergencyCall == null) {
        break missingId;
      }

      id = R.id.welcome_language;
      MaterialButton welcomeLanguage = ViewBindings.findChildViewById(rootView, id);
      if (welcomeLanguage == null) {
        break missingId;
      }

      id = R.id.welcomeLayout;
      RelativeLayout welcomeLayout = ViewBindings.findChildViewById(rootView, id);
      if (welcomeLayout == null) {
        break missingId;
      }

      id = R.id.welcome_text;
      SuperTextView welcomeText = ViewBindings.findChildViewById(rootView, id);
      if (welcomeText == null) {
        break missingId;
      }

      return new FragmentIntroViewBinding((FrameLayout) rootView, banner, welcomeAccessibility,
          welcomeEmergencyCall, welcomeLanguage, welcomeLayout, welcomeText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
